Go2Event/Models/ErrorViewModel.cs
namespace Go2Event.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Go2Event/Controllers/HomeController.cs
using System.Diagnostics;
using Go2Event.Models;
using Microsoft.AspNetCore.Mvc;

namespace Go2Event.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Go2Event/Controllers/OrganizerController.cs
using Microsoft.AspNetCore.Mvc;

namespace Go2Event.Controllers
{
    public class OrganizerController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }
    }
}

Go2Event/Controllers/ParticipantController.cs
using Microsoft.AspNetCore.Mvc;

namespace Go2Event.Controllers
{
    public class ParticipantController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }
    }
}

Go2Event/Views/Home/About.cshtml
@{
	ViewData["Title"] = "About";
}

<div class="box">
	<h1>Go2Event</h1>
	<h2 class="h2">A platform to help organizers and participants on events.</h2>
</div>

Go2Event/Views/Home/Contact.cshtml
@{
	ViewData["Title"] = "Contact";
}

<div class="box">
	<h1>Md. Tanvir Ahmed Siddique</h1>
	<h2 class="h2">tanvir.24633@gmail.com</h2>
	<h2 class="h2">01704476935</h2>
	<p>Sector 10, Uttara, Dhaka, Bangladesh.</p>
</div>

Go2Event/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="box">
    <h1>Welcome to Event2Go.</h1>
    <p>Enhance your experience of events with us.</p>
</div>

<div class="box">
    <a class="button2" asp-controller="Participant" asp-action="Login">Participate an Event</a>
    <a class="button2" asp-controller="Organizer" asp-action="Login">Organize an Event</a>
</div>

Go2Event/Views/Organizer/Login.cshtml
@{
	ViewData["Title"] = "Login";
}

<div class="box">
	<h2>Log in as an Organizer. Enter your credentials.</h2>
	<form>
		<input type="text" class="button2" placeholder="Username" />
		<input type="password" class="button2" placeholder="Password" />
		<input type="submit" class="button3" value="Log in" />
	</form>
	<h2>Don't have an account? <a asp-controller="Organizer" asp-action="Register" class="h2a">Register Now.</a></h2>
</div>

Go2Event/Views/Organizer/Register.cshtml
@{
	ViewData["Title"] = "Register";
}

<div class="box">
	<h2>Register as an Organizer. Enter details.</h2>
	<form>
		<input type="text" class="button2" placeholder="Organization Name" />
		<input type="text" class="button2" placeholder="Address" />
		
		<div class="button2">
			<label>
				<input type="radio" name="type" value="govt" checked> Government
			</label>
			<label>
				<input type="radio" name="type" value="non-govt"> Non-Government
			</label>
		</div>	
		
		<input type="Password" class="button2" placeholder="Password" />

		<input type="submit" class="button3" value="Register" />
	</form>
	<h2>Already have an account? <a asp-controller="Organizer" asp-action="Login" class="h2a">Login Now.</a></h2>
</div>

Go2Event/Views/Participant/Login.cshtml
@{
	ViewData["Title"] = "Login";
}

<div class="box">
	<h2>Log in as a Participant. Enter your credentials.</h2>
	<form>
		<input type="text" class="button2" placeholder="Username" />
		<input type="password" class="button2" placeholder="Password" />
		<input type="submit" class="button3" value="Log in" />
	</form>
	<h2>Don't have an account? <a asp-controller="Participant" asp-action="Register" class="h2a">Register Now.</a></h2>
</div>

Go2Event/Views/Participant/Register.cshtml
@{
	ViewData["Title"] = "Register";
}

<div class="box">
	<h2>Register as a Participant. Enter details.</h2>
	<form>
		<input type="text" class="button2" placeholder="Full Name" />
		
		<div class="button2">
			<label class="makegrey">Date of Birth [	<input type="Date" class="nodesign" /> ]
			</label>
			
		</div>
		
		<div class="button2">
			<label>
				<input type="radio" name="gender" value="male" checked> Male
			</label>
			<label>
				<input type="radio" name="gender" value="female"> Female
			</label>
		</div>	

		<input type="Password" class="button2" placeholder="Password" />
		
		<input type="submit" class="button3" value="Register" />
	</form>
	<h2>Already have an account? <a asp-controller="Participant" asp-action="Login" class="h2a">Login Now.</a></h2>
</div>

Go2Event/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Go2Event</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Go2Event.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <a class="homebutton" asp-controller="Home" asp-action="Index">Go2Event</a>
        <a class="button" asp-controller="Home" asp-action="Contact">Contact Us</a>
        <a class="button" asp-controller="Home" asp-action="About">About Us</a>
    </header>

    <div class="maincontent">
        @RenderBody()
    </div>

    <footer>
            &copy; 2026 - Go2Event is owned by <b>Tanvir Ahemd</b> - <a asp-area="" asp-controller="Home" asp-action="Privacy">Learn more</a>.
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>